### ISSUE TITLE
프론트 스터디

### ISSUE THREAD

**Issue by Biccon** [Konkuk-JJabaries/ReactJS-Study#11]
- [x] 1주차 스터디 - 김동언
- [x] 1주차 스터디 - 박우진
- [x] 2주차 스터디 - 김동언
- [x] 2주차 스터디 - 박우진
- [x] 3주차 스터디 - 김동언
- [x] 3주차 스터디 - 박우진

**Comment by Biccon** [comment]
1주차 스터디
- op.gg 게시판 목록 만들기

**Comment by wjp103** [comment]
1주차 스터디

- calender 만들기 ( 1달 )

**Comment by Biccon** [comment]
2주차 스터디
- op.gg 게시글 목록 만들기

**Comment by wjp103** [comment]
2주차 스터디
- 버튼리스너 동작 추가
- date type 변수를 가지고 props 주고받기.

**Comment by wjp103** [comment]
3주차 스터디
- modal 화면 추가
- Schedule_title Component 추가 및 달력 css 추가
- toy project finish
